---
title: "Análisis y Modelado Espacial (Presentaciones)"
description: "Licenciatura en Ecología"
author: "Gerardo Martín"
output:
   prettydoc::html_pretty:
      theme: caiman
      highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- [Encuadre](Encuadre.pdf)
- [Programa del curso](Programa.pdf)
- [Calendario de participación](Calendario-participacion.pdf)
    
1. [Introducción al Modelado Espacial](Unidad-1/Introduccion.pdf)

    - [Análisis utilizando sistemas de información geográfica](Unidad-1/Analisis-SIG.pdf)
    
    - [Modelado espacial](Unidad-1/Modelado-espacial.pdf)
          
2. [Análisis de la asociación espacial entre varios fenómenos](Unidad-2/Intro-asociacion.pdf)

    - [Correlación](Unidad-2/Correlacion.pdf) ([Código fuente de la presentación](Unidad-2/Correlacion.Rmd))
    
    - [Correlación espacial](Unidad-2/Correlacion-espacial.pdf)
    
    - [Regresión espacial](Unidad-2/Regresion.pdf)
    
    - [Asociación con el espacio](Unidad-2/Asociacion-espacio.pdf)
    
    - [Usos del índice de Moran](Unidad-2/Usos-Moran.pdf)
    
    - [Interpolación](Unidad-2/Interpolacion.pdf)
    
    - [Tutorial 2 de interpolación](Unidad-2/Tutorial-splines-IDW.html)
    
3. Modelado de áreas de distribución y nichos ecológicos

    - [Nociones de nicho ecológico](Unidad-3/Nociones.pdf)

    - [Métodos para modelación de áreas y nichos](Unidad-3/Metodos.pdf)
    
    - [Usos de los modelos de áreas de distribución y nicho ecológico](Unidad-3/Usos.pdf)
    
